//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvvmframework.Languages {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Langs {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("mvvmframework.Languages.Langs", typeof(Langs).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Const_Title_Error_1 {
            get {
                return ResourceManager.GetString("Const_Title_Error_1", resourceCulture);
            }
        }
        
        public static string Const_Title_Error_2 {
            get {
                return ResourceManager.GetString("Const_Title_Error_2", resourceCulture);
            }
        }
        
        public static string Const_Title_Error_3 {
            get {
                return ResourceManager.GetString("Const_Title_Error_3", resourceCulture);
            }
        }
        
        public static string Const_Title_Completed {
            get {
                return ResourceManager.GetString("Const_Title_Completed", resourceCulture);
            }
        }
        
        public static string Const_Title_Are_You_Sure {
            get {
                return ResourceManager.GetString("Const_Title_Are_You_Sure", resourceCulture);
            }
        }
        
        public static string Const_Msg_Invalid_Email {
            get {
                return ResourceManager.GetString("Const_Msg_Invalid_Email", resourceCulture);
            }
        }
        
        public static string Const_Msg_Already_Exist {
            get {
                return ResourceManager.GetString("Const_Msg_Already_Exist", resourceCulture);
            }
        }
        
        public static string Const_Msg_UnknownError {
            get {
                return ResourceManager.GetString("Const_Msg_UnknownError", resourceCulture);
            }
        }
        
        public static string Const_Msg_Password_Send {
            get {
                return ResourceManager.GetString("Const_Msg_Password_Send", resourceCulture);
            }
        }
        
        public static string Const_Msg_Forgot_Password_Desc {
            get {
                return ResourceManager.GetString("Const_Msg_Forgot_Password_Desc", resourceCulture);
            }
        }
        
        public static string Const_Msg_Private_Mode_Selection {
            get {
                return ResourceManager.GetString("Const_Msg_Private_Mode_Selection", resourceCulture);
            }
        }
        
        public static string Const_Msg_Waiting {
            get {
                return ResourceManager.GetString("Const_Msg_Waiting", resourceCulture);
            }
        }
        
        public static string Const_Msg_Marketing {
            get {
                return ResourceManager.GetString("Const_Msg_Marketing", resourceCulture);
            }
        }
        
        public static string Const_Msg_Password_Not_Matching {
            get {
                return ResourceManager.GetString("Const_Msg_Password_Not_Matching", resourceCulture);
            }
        }
        
        public static string Const_Msg_New_Password_Not_Matching {
            get {
                return ResourceManager.GetString("Const_Msg_New_Password_Not_Matching", resourceCulture);
            }
        }
        
        public static string Const_Msg_Password_Invalid {
            get {
                return ResourceManager.GetString("Const_Msg_Password_Invalid", resourceCulture);
            }
        }
        
        public static string Const_Msg_Old_Password_Incorrect {
            get {
                return ResourceManager.GetString("Const_Msg_Old_Password_Incorrect", resourceCulture);
            }
        }
        
        public static string Const_Msg_NavigateTo_Login {
            get {
                return ResourceManager.GetString("Const_Msg_NavigateTo_Login", resourceCulture);
            }
        }
        
        public static string Const_Msg_Registration_Completed {
            get {
                return ResourceManager.GetString("Const_Msg_Registration_Completed", resourceCulture);
            }
        }
        
        public static string Const_Msg_Registration_Completed_Description {
            get {
                return ResourceManager.GetString("Const_Msg_Registration_Completed_Description", resourceCulture);
            }
        }
        
        public static string Const_Msg_Registration_Completed_Pair_Vehicle {
            get {
                return ResourceManager.GetString("Const_Msg_Registration_Completed_Pair_Vehicle", resourceCulture);
            }
        }
        
        public static string Const_Msg_No_Map_Data {
            get {
                return ResourceManager.GetString("Const_Msg_No_Map_Data", resourceCulture);
            }
        }
        
        public static string Const_Msg_Private_Mode_Enabled_1 {
            get {
                return ResourceManager.GetString("Const_Msg_Private_Mode_Enabled_1", resourceCulture);
            }
        }
        
        public static string Const_Msg_Private_Mode_Enabled_2 {
            get {
                return ResourceManager.GetString("Const_Msg_Private_Mode_Enabled_2", resourceCulture);
            }
        }
        
        public static string Const_Msg_Private_Mode_Enabled_3 {
            get {
                return ResourceManager.GetString("Const_Msg_Private_Mode_Enabled_3", resourceCulture);
            }
        }
        
        public static string Const_Msg_Select_Date_Range_1 {
            get {
                return ResourceManager.GetString("Const_Msg_Select_Date_Range_1", resourceCulture);
            }
        }
        
        public static string Const_Msg_Select_Date_Range_2 {
            get {
                return ResourceManager.GetString("Const_Msg_Select_Date_Range_2", resourceCulture);
            }
        }
        
        public static string Const_Msg_Select_Vehicle {
            get {
                return ResourceManager.GetString("Const_Msg_Select_Vehicle", resourceCulture);
            }
        }
        
        public static string Const_Msg_Private_Mode_Desc {
            get {
                return ResourceManager.GetString("Const_Msg_Private_Mode_Desc", resourceCulture);
            }
        }
        
        public static string Const_Msg_Access_Code_Desc {
            get {
                return ResourceManager.GetString("Const_Msg_Access_Code_Desc", resourceCulture);
            }
        }
        
        public static string Const_Msg_Success_Enter_Fleet_Code {
            get {
                return ResourceManager.GetString("Const_Msg_Success_Enter_Fleet_Code", resourceCulture);
            }
        }
        
        public static string Const_Msg_Success_Change_Phone_Number {
            get {
                return ResourceManager.GetString("Const_Msg_Success_Change_Phone_Number", resourceCulture);
            }
        }
        
        public static string Const_Msg_Success_Change_Password {
            get {
                return ResourceManager.GetString("Const_Msg_Success_Change_Password", resourceCulture);
            }
        }
        
        public static string Const_Msg_Success_Enter_Odometer_Reding {
            get {
                return ResourceManager.GetString("Const_Msg_Success_Enter_Odometer_Reding", resourceCulture);
            }
        }
        
        public static string Const_Msg_Cannot_Send_Email {
            get {
                return ResourceManager.GetString("Const_Msg_Cannot_Send_Email", resourceCulture);
            }
        }
        
        public static string Const_Msg_Screen_Locked {
            get {
                return ResourceManager.GetString("Const_Msg_Screen_Locked", resourceCulture);
            }
        }
        
        public static string Const_Msg_Server_Connection_Error {
            get {
                return ResourceManager.GetString("Const_Msg_Server_Connection_Error", resourceCulture);
            }
        }
        
        public static string Const_Msg_SOS_1 {
            get {
                return ResourceManager.GetString("Const_Msg_SOS_1", resourceCulture);
            }
        }
        
        public static string Const_Msg_SOS_2 {
            get {
                return ResourceManager.GetString("Const_Msg_SOS_2", resourceCulture);
            }
        }
        
        public static string Const_Msg_Disagree_Failed {
            get {
                return ResourceManager.GetString("Const_Msg_Disagree_Failed", resourceCulture);
            }
        }
        
        public static string Const_Msg_Disagree_Success {
            get {
                return ResourceManager.GetString("Const_Msg_Disagree_Success", resourceCulture);
            }
        }
        
        public static string Const_Msg_Help_Disagree {
            get {
                return ResourceManager.GetString("Const_Msg_Help_Disagree", resourceCulture);
            }
        }
        
        public static string Const_Msg_Pair_Vehicle_Description_1 {
            get {
                return ResourceManager.GetString("Const_Msg_Pair_Vehicle_Description_1", resourceCulture);
            }
        }
        
        public static string Const_Msg_Pair_Vehicle_Description_2 {
            get {
                return ResourceManager.GetString("Const_Msg_Pair_Vehicle_Description_2", resourceCulture);
            }
        }
        
        public static string Const_Msg_Pair_Vehicle_Help_Description_1 {
            get {
                return ResourceManager.GetString("Const_Msg_Pair_Vehicle_Help_Description_1", resourceCulture);
            }
        }
        
        public static string Const_Msg_Pair_Vehicle_Help_Description_2 {
            get {
                return ResourceManager.GetString("Const_Msg_Pair_Vehicle_Help_Description_2", resourceCulture);
            }
        }
        
        public static string Const_Msg_Pair_Vehicle_Help_Description_3 {
            get {
                return ResourceManager.GetString("Const_Msg_Pair_Vehicle_Help_Description_3", resourceCulture);
            }
        }
        
        public static string Const_Msg_Pair_Vehicle_Help_Description_4 {
            get {
                return ResourceManager.GetString("Const_Msg_Pair_Vehicle_Help_Description_4", resourceCulture);
            }
        }
        
        public static string Const_Msg_Registration_Step_1_Help_Description {
            get {
                return ResourceManager.GetString("Const_Msg_Registration_Step_1_Help_Description", resourceCulture);
            }
        }
        
        public static string Const_Msg_Registration_Step_2_Help_Description {
            get {
                return ResourceManager.GetString("Const_Msg_Registration_Step_2_Help_Description", resourceCulture);
            }
        }
        
        public static string Const_Msg_Registration_Step_3_Help_Description {
            get {
                return ResourceManager.GetString("Const_Msg_Registration_Step_3_Help_Description", resourceCulture);
            }
        }
        
        public static string Const_Msg_Registration_Step_4_Help_Description {
            get {
                return ResourceManager.GetString("Const_Msg_Registration_Step_4_Help_Description", resourceCulture);
            }
        }
        
        public static string Const_Msg_Registration_Email_Exist {
            get {
                return ResourceManager.GetString("Const_Msg_Registration_Email_Exist", resourceCulture);
            }
        }
        
        public static string Const_Msg_Journey_Error {
            get {
                return ResourceManager.GetString("Const_Msg_Journey_Error", resourceCulture);
            }
        }
        
        public static string Const_Msg_No_Journeys {
            get {
                return ResourceManager.GetString("Const_Msg_No_Journeys", resourceCulture);
            }
        }
        
        public static string Const_Msg_Terms_Description {
            get {
                return ResourceManager.GetString("Const_Msg_Terms_Description", resourceCulture);
            }
        }
        
        public static string Const_Msg_Odometer_Description_1 {
            get {
                return ResourceManager.GetString("Const_Msg_Odometer_Description_1", resourceCulture);
            }
        }
        
        public static string Const_Msg_Odometer_Description_2 {
            get {
                return ResourceManager.GetString("Const_Msg_Odometer_Description_2", resourceCulture);
            }
        }
        
        public static string Const_Msg_Export_No_Journey {
            get {
                return ResourceManager.GetString("Const_Msg_Export_No_Journey", resourceCulture);
            }
        }
        
        public static string Const_Msg_SOS_Title_1 {
            get {
                return ResourceManager.GetString("Const_Msg_SOS_Title_1", resourceCulture);
            }
        }
        
        public static string Const_Msg_SOS_Title_2 {
            get {
                return ResourceManager.GetString("Const_Msg_SOS_Title_2", resourceCulture);
            }
        }
        
        public static string Const_Msg_SOS_Title_3 {
            get {
                return ResourceManager.GetString("Const_Msg_SOS_Title_3", resourceCulture);
            }
        }
        
        public static string Const_Msg_SOS_Title_4 {
            get {
                return ResourceManager.GetString("Const_Msg_SOS_Title_4", resourceCulture);
            }
        }
        
        public static string Const_Msg_SOS_Title_5 {
            get {
                return ResourceManager.GetString("Const_Msg_SOS_Title_5", resourceCulture);
            }
        }
        
        public static string Const_Msg_SOS_Title_6 {
            get {
                return ResourceManager.GetString("Const_Msg_SOS_Title_6", resourceCulture);
            }
        }
        
        public static string Const_Msg_SOS_Title_7 {
            get {
                return ResourceManager.GetString("Const_Msg_SOS_Title_7", resourceCulture);
            }
        }
        
        public static string Const_Msg_SOS_Description_1 {
            get {
                return ResourceManager.GetString("Const_Msg_SOS_Description_1", resourceCulture);
            }
        }
        
        public static string Const_Msg_SOS_Description_2 {
            get {
                return ResourceManager.GetString("Const_Msg_SOS_Description_2", resourceCulture);
            }
        }
        
        public static string Const_Msg_SOS_Description_3 {
            get {
                return ResourceManager.GetString("Const_Msg_SOS_Description_3", resourceCulture);
            }
        }
        
        public static string Const_Msg_SOS_Description_4 {
            get {
                return ResourceManager.GetString("Const_Msg_SOS_Description_4", resourceCulture);
            }
        }
        
        public static string Const_Msg_SOS_Description_5 {
            get {
                return ResourceManager.GetString("Const_Msg_SOS_Description_5", resourceCulture);
            }
        }
        
        public static string Const_Msg_SOS_Description_6 {
            get {
                return ResourceManager.GetString("Const_Msg_SOS_Description_6", resourceCulture);
            }
        }
        
        public static string Const_Msg_SOS_Description_7 {
            get {
                return ResourceManager.GetString("Const_Msg_SOS_Description_7", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Terms {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Terms", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Registration_1 {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Registration_1", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Registration_2 {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Registration_2", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Registration_3 {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Registration_3", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Registration_4 {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Registration_4", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Registration_Completed {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Registration_Completed", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Forgot_Password {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Forgot_Password", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Dashboard {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Dashboard", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Score_History {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Score_History", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Journeys {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Journeys", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Expenses {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Expenses", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Settings {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Settings", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Change_Password {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Change_Password", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Phone_Number {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Phone_Number", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Fleet_Code {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Fleet_Code", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Odometer_Reading {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Odometer_Reading", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Marketing_Preferences {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Marketing_Preferences", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_About {
            get {
                return ResourceManager.GetString("Const_Screen_Title_About", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_SOS {
            get {
                return ResourceManager.GetString("Const_Screen_Title_SOS", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_My_Profile {
            get {
                return ResourceManager.GetString("Const_Screen_Title_My_Profile", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Vehicles {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Vehicles", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Add_Vehicle {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Add_Vehicle", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Pair_Vehicle {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Pair_Vehicle", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Notifications {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Notifications", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Language {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Language", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Log_Files {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Log_Files", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Manage_Vehicle {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Manage_Vehicle", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Select_Vehicle {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Select_Vehicle", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Select_Bluetooth {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Select_Bluetooth", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Pairing_Summary {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Pairing_Summary", resourceCulture);
            }
        }
        
        public static string Const_Screen_Title_Pairing_Completed {
            get {
                return ResourceManager.GetString("Const_Screen_Title_Pairing_Completed", resourceCulture);
            }
        }
        
        public static string Const_Label_Agree_1 {
            get {
                return ResourceManager.GetString("Const_Label_Agree_1", resourceCulture);
            }
        }
        
        public static string Const_Label_Agree_2 {
            get {
                return ResourceManager.GetString("Const_Label_Agree_2", resourceCulture);
            }
        }
        
        public static string Const_Label_Disagree {
            get {
                return ResourceManager.GetString("Const_Label_Disagree", resourceCulture);
            }
        }
        
        public static string Const_Label_First_Name {
            get {
                return ResourceManager.GetString("Const_Label_First_Name", resourceCulture);
            }
        }
        
        public static string Const_Label_Last_Name {
            get {
                return ResourceManager.GetString("Const_Label_Last_Name", resourceCulture);
            }
        }
        
        public static string Const_Label_DOB {
            get {
                return ResourceManager.GetString("Const_Label_DOB", resourceCulture);
            }
        }
        
        public static string Const_Label_Mobile_Number {
            get {
                return ResourceManager.GetString("Const_Label_Mobile_Number", resourceCulture);
            }
        }
        
        public static string Const_Label_Company_Name {
            get {
                return ResourceManager.GetString("Const_Label_Company_Name", resourceCulture);
            }
        }
        
        public static string Const_Label_Position {
            get {
                return ResourceManager.GetString("Const_Label_Position", resourceCulture);
            }
        }
        
        public static string Const_Label_Email_1 {
            get {
                return ResourceManager.GetString("Const_Label_Email_1", resourceCulture);
            }
        }
        
        public static string Const_Label_Email_2 {
            get {
                return ResourceManager.GetString("Const_Label_Email_2", resourceCulture);
            }
        }
        
        public static string Const_Label_Access_Code {
            get {
                return ResourceManager.GetString("Const_Label_Access_Code", resourceCulture);
            }
        }
        
        public static string Const_Label_ReEnter {
            get {
                return ResourceManager.GetString("Const_Label_ReEnter", resourceCulture);
            }
        }
        
        public static string Const_Label_Show_Password {
            get {
                return ResourceManager.GetString("Const_Label_Show_Password", resourceCulture);
            }
        }
        
        public static string Const_Label_Hide_Password {
            get {
                return ResourceManager.GetString("Const_Label_Hide_Password", resourceCulture);
            }
        }
        
        public static string Const_Label_Forgot_Password {
            get {
                return ResourceManager.GetString("Const_Label_Forgot_Password", resourceCulture);
            }
        }
        
        public static string Const_Label_Register {
            get {
                return ResourceManager.GetString("Const_Label_Register", resourceCulture);
            }
        }
        
        public static string Const_Label_Loading {
            get {
                return ResourceManager.GetString("Const_Label_Loading", resourceCulture);
            }
        }
        
        public static string Const_Label_Password {
            get {
                return ResourceManager.GetString("Const_Label_Password", resourceCulture);
            }
        }
        
        public static string Const_Label_Previous {
            get {
                return ResourceManager.GetString("Const_Label_Previous", resourceCulture);
            }
        }
        
        public static string Const_Label_Next {
            get {
                return ResourceManager.GetString("Const_Label_Next", resourceCulture);
            }
        }
        
        public static string Const_Label_Done {
            get {
                return ResourceManager.GetString("Const_Label_Done", resourceCulture);
            }
        }
        
        public static string Const_Label_Vehicle_Nickname {
            get {
                return ResourceManager.GetString("Const_Label_Vehicle_Nickname", resourceCulture);
            }
        }
        
        public static string Const_Label_Bluetooth_Completed {
            get {
                return ResourceManager.GetString("Const_Label_Bluetooth_Completed", resourceCulture);
            }
        }
        
        public static string Const_Label_Latest_Journey_Miles {
            get {
                return ResourceManager.GetString("Const_Label_Latest_Journey_Miles", resourceCulture);
            }
        }
        
        public static string Const_Label_Latest_Driver_Score {
            get {
                return ResourceManager.GetString("Const_Label_Latest_Driver_Score", resourceCulture);
            }
        }
        
        public static string Const_Label_Latest_Driver_Journey {
            get {
                return ResourceManager.GetString("Const_Label_Latest_Driver_Journey", resourceCulture);
            }
        }
        
        public static string Const_Label_Latest_Odometer {
            get {
                return ResourceManager.GetString("Const_Label_Latest_Odometer", resourceCulture);
            }
        }
        
        public static string Const_Label_Speed {
            get {
                return ResourceManager.GetString("Const_Label_Speed", resourceCulture);
            }
        }
        
        public static string Const_Label_Smoothness {
            get {
                return ResourceManager.GetString("Const_Label_Smoothness", resourceCulture);
            }
        }
        
        public static string Const_Label_Usage {
            get {
                return ResourceManager.GetString("Const_Label_Usage", resourceCulture);
            }
        }
        
        public static string Const_Label_Miles {
            get {
                return ResourceManager.GetString("Const_Label_Miles", resourceCulture);
            }
        }
        
        public static string Gen_Const_Label_Current_Rank {
            get {
                return ResourceManager.GetString("Gen_Const_Label_Current_Rank", resourceCulture);
            }
        }
        
        public static string Const_Label_Average_Fleet_Score {
            get {
                return ResourceManager.GetString("Const_Label_Average_Fleet_Score", resourceCulture);
            }
        }
        
        public static string Const_Label_Average_Fleet_Score_Desc {
            get {
                return ResourceManager.GetString("Const_Label_Average_Fleet_Score_Desc", resourceCulture);
            }
        }
        
        public static string Const_Label_Your_Difference {
            get {
                return ResourceManager.GetString("Const_Label_Your_Difference", resourceCulture);
            }
        }
        
        public static string Const_Label_Your_Score {
            get {
                return ResourceManager.GetString("Const_Label_Your_Score", resourceCulture);
            }
        }
        
        public static string Const_Label_Fleet_Score {
            get {
                return ResourceManager.GetString("Const_Label_Fleet_Score", resourceCulture);
            }
        }
        
        public static string Const_Label_Private_Mode {
            get {
                return ResourceManager.GetString("Const_Label_Private_Mode", resourceCulture);
            }
        }
        
        public static string Const_Label_Private_Mode_On {
            get {
                return ResourceManager.GetString("Const_Label_Private_Mode_On", resourceCulture);
            }
        }
        
        public static string Const_Label_Private_Mode_On_Desc {
            get {
                return ResourceManager.GetString("Const_Label_Private_Mode_On_Desc", resourceCulture);
            }
        }
        
        public static string Const_Label_Swipe {
            get {
                return ResourceManager.GetString("Const_Label_Swipe", resourceCulture);
            }
        }
        
        public static string Const_Label_Score_Week {
            get {
                return ResourceManager.GetString("Const_Label_Score_Week", resourceCulture);
            }
        }
        
        public static string Const_Label_Week_Commence {
            get {
                return ResourceManager.GetString("Const_Label_Week_Commence", resourceCulture);
            }
        }
        
        public static string Const_Label_Week_End {
            get {
                return ResourceManager.GetString("Const_Label_Week_End", resourceCulture);
            }
        }
        
        public static string Const_Label_More {
            get {
                return ResourceManager.GetString("Const_Label_More", resourceCulture);
            }
        }
        
        public static string Const_Label_Less {
            get {
                return ResourceManager.GetString("Const_Label_Less", resourceCulture);
            }
        }
        
        public static string Const_Label_Zone {
            get {
                return ResourceManager.GetString("Const_Label_Zone", resourceCulture);
            }
        }
        
        public static string Const_Label_Change_Password {
            get {
                return ResourceManager.GetString("Const_Label_Change_Password", resourceCulture);
            }
        }
        
        public static string Const_Label_Phone_Number {
            get {
                return ResourceManager.GetString("Const_Label_Phone_Number", resourceCulture);
            }
        }
        
        public static string Const_Label_Enter_Fleet_Code {
            get {
                return ResourceManager.GetString("Const_Label_Enter_Fleet_Code", resourceCulture);
            }
        }
        
        public static string Const_Label_Enter_Odometer_Readings {
            get {
                return ResourceManager.GetString("Const_Label_Enter_Odometer_Readings", resourceCulture);
            }
        }
        
        public static string Const_Label_Marketing_Preferences {
            get {
                return ResourceManager.GetString("Const_Label_Marketing_Preferences", resourceCulture);
            }
        }
        
        public static string Const_Label_Language_Preferences {
            get {
                return ResourceManager.GetString("Const_Label_Language_Preferences", resourceCulture);
            }
        }
        
        public static string Const_Label_Log_File {
            get {
                return ResourceManager.GetString("Const_Label_Log_File", resourceCulture);
            }
        }
        
        public static string Const_Label_Log_Files {
            get {
                return ResourceManager.GetString("Const_Label_Log_Files", resourceCulture);
            }
        }
        
        public static string Const_Label_About {
            get {
                return ResourceManager.GetString("Const_Label_About", resourceCulture);
            }
        }
        
        public static string Const_Label_Current_Password {
            get {
                return ResourceManager.GetString("Const_Label_Current_Password", resourceCulture);
            }
        }
        
        public static string Const_Label_New_Password {
            get {
                return ResourceManager.GetString("Const_Label_New_Password", resourceCulture);
            }
        }
        
        public static string Const_Label_Cancel {
            get {
                return ResourceManager.GetString("Const_Label_Cancel", resourceCulture);
            }
        }
        
        public static string Const_Label_Fleet_Code {
            get {
                return ResourceManager.GetString("Const_Label_Fleet_Code", resourceCulture);
            }
        }
        
        public static string Const_Label_Odometer {
            get {
                return ResourceManager.GetString("Const_Label_Odometer", resourceCulture);
            }
        }
        
        public static string Const_Label_Date {
            get {
                return ResourceManager.GetString("Const_Label_Date", resourceCulture);
            }
        }
        
        public static string Const_Label_Hour {
            get {
                return ResourceManager.GetString("Const_Label_Hour", resourceCulture);
            }
        }
        
        public static string Const_Label_Minutes {
            get {
                return ResourceManager.GetString("Const_Label_Minutes", resourceCulture);
            }
        }
        
        public static string Const_Label_Version {
            get {
                return ResourceManager.GetString("Const_Label_Version", resourceCulture);
            }
        }
        
        public static string Const_Label_Installed {
            get {
                return ResourceManager.GetString("Const_Label_Installed", resourceCulture);
            }
        }
        
        public static string Const_Label_About_Description {
            get {
                return ResourceManager.GetString("Const_Label_About_Description", resourceCulture);
            }
        }
        
        public static string Const_Label_About_Company_Number {
            get {
                return ResourceManager.GetString("Const_Label_About_Company_Number", resourceCulture);
            }
        }
        
        public static string Const_Label_Guide_Steps {
            get {
                return ResourceManager.GetString("Const_Label_Guide_Steps", resourceCulture);
            }
        }
        
        public static string Const_Label_Guide_Tip {
            get {
                return ResourceManager.GetString("Const_Label_Guide_Tip", resourceCulture);
            }
        }
        
        public static string Const_Label_Manage_Vehicles {
            get {
                return ResourceManager.GetString("Const_Label_Manage_Vehicles", resourceCulture);
            }
        }
        
        public static string Const_Label_Notifications {
            get {
                return ResourceManager.GetString("Const_Label_Notifications", resourceCulture);
            }
        }
        
        public static string Const_Label_New_Notification {
            get {
                return ResourceManager.GetString("Const_Label_New_Notification", resourceCulture);
            }
        }
        
        public static string Const_Label_New_Notifications {
            get {
                return ResourceManager.GetString("Const_Label_New_Notifications", resourceCulture);
            }
        }
        
        public static string Const_Label_Notifications_Popup {
            get {
                return ResourceManager.GetString("Const_Label_Notifications_Popup", resourceCulture);
            }
        }
        
        public static string Const_Label_Select_Vehicle {
            get {
                return ResourceManager.GetString("Const_Label_Select_Vehicle", resourceCulture);
            }
        }
        
        public static string Const_Label_Select_Bluetooth {
            get {
                return ResourceManager.GetString("Const_Label_Select_Bluetooth", resourceCulture);
            }
        }
        
        public static string Const_Label_Paired_Vehicles {
            get {
                return ResourceManager.GetString("Const_Label_Paired_Vehicles", resourceCulture);
            }
        }
        
        public static string Const_Label_Pair_New_Vehicle {
            get {
                return ResourceManager.GetString("Const_Label_Pair_New_Vehicle", resourceCulture);
            }
        }
        
        public static string Const_Label_Pair_Bluetooth {
            get {
                return ResourceManager.GetString("Const_Label_Pair_Bluetooth", resourceCulture);
            }
        }
        
        public static string Const_Label_Add_Vehicle {
            get {
                return ResourceManager.GetString("Const_Label_Add_Vehicle", resourceCulture);
            }
        }
        
        public static string Const_Label_Confirm_Selection {
            get {
                return ResourceManager.GetString("Const_Label_Confirm_Selection", resourceCulture);
            }
        }
        
        public static string Const_Label_Confirm_Language {
            get {
                return ResourceManager.GetString("Const_Label_Confirm_Language", resourceCulture);
            }
        }
        
        public static string Const_Label_Confirm {
            get {
                return ResourceManager.GetString("Const_Label_Confirm", resourceCulture);
            }
        }
        
        public static string Const_Label_Registration {
            get {
                return ResourceManager.GetString("Const_Label_Registration", resourceCulture);
            }
        }
        
        public static string Const_Label_Make {
            get {
                return ResourceManager.GetString("Const_Label_Make", resourceCulture);
            }
        }
        
        public static string Const_Label_Model {
            get {
                return ResourceManager.GetString("Const_Label_Model", resourceCulture);
            }
        }
        
        public static string Const_Label_Name {
            get {
                return ResourceManager.GetString("Const_Label_Name", resourceCulture);
            }
        }
        
        public static string Const_Label_Unread {
            get {
                return ResourceManager.GetString("Const_Label_Unread", resourceCulture);
            }
        }
        
        public static string Const_Label_Warning {
            get {
                return ResourceManager.GetString("Const_Label_Warning", resourceCulture);
            }
        }
        
        public static string Const_Label_Warnings {
            get {
                return ResourceManager.GetString("Const_Label_Warnings", resourceCulture);
            }
        }
        
        public static string Const_Label_View {
            get {
                return ResourceManager.GetString("Const_Label_View", resourceCulture);
            }
        }
        
        public static string Const_Label_Terms_Scroll {
            get {
                return ResourceManager.GetString("Const_Label_Terms_Scroll", resourceCulture);
            }
        }
        
        public static string Const_Label_Select {
            get {
                return ResourceManager.GetString("Const_Label_Select", resourceCulture);
            }
        }
        
        public static string Const_Label_Deselect {
            get {
                return ResourceManager.GetString("Const_Label_Deselect", resourceCulture);
            }
        }
        
        public static string Const_Label_Overall_Journey_Score {
            get {
                return ResourceManager.GetString("Const_Label_Overall_Journey_Score", resourceCulture);
            }
        }
        
        public static string Const_Label_Enter_Speed {
            get {
                return ResourceManager.GetString("Const_Label_Enter_Speed", resourceCulture);
            }
        }
        
        public static string Const_Label_Fleet_Code_Question {
            get {
                return ResourceManager.GetString("Const_Label_Fleet_Code_Question", resourceCulture);
            }
        }
        
        public static string Const_Label_Disable_Fleet_Code {
            get {
                return ResourceManager.GetString("Const_Label_Disable_Fleet_Code", resourceCulture);
            }
        }
        
        public static string Const_Label_Manage_Vehicle_Step_1 {
            get {
                return ResourceManager.GetString("Const_Label_Manage_Vehicle_Step_1", resourceCulture);
            }
        }
        
        public static string Const_Label_Manage_Vehicle_Step_2 {
            get {
                return ResourceManager.GetString("Const_Label_Manage_Vehicle_Step_2", resourceCulture);
            }
        }
        
        public static string Const_Label_Manage_Vehicle_Step_3 {
            get {
                return ResourceManager.GetString("Const_Label_Manage_Vehicle_Step_3", resourceCulture);
            }
        }
        
        public static string Const_Label_No_Search_Result {
            get {
                return ResourceManager.GetString("Const_Label_No_Search_Result", resourceCulture);
            }
        }
        
        public static string Const_Label_Skip_Fleet_Code {
            get {
                return ResourceManager.GetString("Const_Label_Skip_Fleet_Code", resourceCulture);
            }
        }
        
        public static string Const_Label_Pairing {
            get {
                return ResourceManager.GetString("Const_Label_Pairing", resourceCulture);
            }
        }
        
        public static string Const_Label_Review_Info {
            get {
                return ResourceManager.GetString("Const_Label_Review_Info", resourceCulture);
            }
        }
        
        public static string Const_Label_Bluetooth_Registered {
            get {
                return ResourceManager.GetString("Const_Label_Bluetooth_Registered", resourceCulture);
            }
        }
        
        public static string Const_Label_Confirm_Pairing {
            get {
                return ResourceManager.GetString("Const_Label_Confirm_Pairing", resourceCulture);
            }
        }
        
        public static string Const_Label_Pairing_Completed {
            get {
                return ResourceManager.GetString("Const_Label_Pairing_Completed", resourceCulture);
            }
        }
        
        public static string Const_Label_Turn_On_Location_Services {
            get {
                return ResourceManager.GetString("Const_Label_Turn_On_Location_Services", resourceCulture);
            }
        }
        
        public static string Const_Label_Turn_On_Bluetooth {
            get {
                return ResourceManager.GetString("Const_Label_Turn_On_Bluetooth", resourceCulture);
            }
        }
        
        public static string Const_Label_Calendar {
            get {
                return ResourceManager.GetString("Const_Label_Calendar", resourceCulture);
            }
        }
        
        public static string Const_Label_Overall_Driver_Score {
            get {
                return ResourceManager.GetString("Const_Label_Overall_Driver_Score", resourceCulture);
            }
        }
        
        public static string Const_Label_Total_Mileage {
            get {
                return ResourceManager.GetString("Const_Label_Total_Mileage", resourceCulture);
            }
        }
        
        public static string Const_Label_Business {
            get {
                return ResourceManager.GetString("Const_Label_Business", resourceCulture);
            }
        }
        
        public static string Const_Label_Private {
            get {
                return ResourceManager.GetString("Const_Label_Private", resourceCulture);
            }
        }
        
        public static string Const_Label_Registration_Title {
            get {
                return ResourceManager.GetString("Const_Label_Registration_Title", resourceCulture);
            }
        }
        
        public static string Const_Label_Registration_Description {
            get {
                return ResourceManager.GetString("Const_Label_Registration_Description", resourceCulture);
            }
        }
        
        public static string Const_Label_Show_Private_Off {
            get {
                return ResourceManager.GetString("Const_Label_Show_Private_Off", resourceCulture);
            }
        }
        
        public static string Const_Label_Show_Private_On {
            get {
                return ResourceManager.GetString("Const_Label_Show_Private_On", resourceCulture);
            }
        }
        
        public static string Const_Label_Fleet_Rank {
            get {
                return ResourceManager.GetString("Const_Label_Fleet_Rank", resourceCulture);
            }
        }
        
        public static string Const_Label_Group_Rank {
            get {
                return ResourceManager.GetString("Const_Label_Group_Rank", resourceCulture);
            }
        }
        
        public static string Const_Label_Team_Rank {
            get {
                return ResourceManager.GetString("Const_Label_Team_Rank", resourceCulture);
            }
        }
        
        public static string Const_Label_Business_Rank {
            get {
                return ResourceManager.GetString("Const_Label_Business_Rank", resourceCulture);
            }
        }
        
        public static string Const_Label_Rank_Average_Fleet_Score {
            get {
                return ResourceManager.GetString("Const_Label_Rank_Average_Fleet_Score", resourceCulture);
            }
        }
        
        public static string Const_Label_Latest_Journey {
            get {
                return ResourceManager.GetString("Const_Label_Latest_Journey", resourceCulture);
            }
        }
        
        public static string Const_Label_Business_Mileage {
            get {
                return ResourceManager.GetString("Const_Label_Business_Mileage", resourceCulture);
            }
        }
        
        public static string Const_Label_Personal_Mileage {
            get {
                return ResourceManager.GetString("Const_Label_Personal_Mileage", resourceCulture);
            }
        }
        
        public static string Const_Label_Terms_1 {
            get {
                return ResourceManager.GetString("Const_Label_Terms_1", resourceCulture);
            }
        }
        
        public static string Const_Label_Terms_2 {
            get {
                return ResourceManager.GetString("Const_Label_Terms_2", resourceCulture);
            }
        }
        
        public static string Const_Label_Terms_3 {
            get {
                return ResourceManager.GetString("Const_Label_Terms_3", resourceCulture);
            }
        }
        
        public static string Const_Label_Driver_Score {
            get {
                return ResourceManager.GetString("Const_Label_Driver_Score", resourceCulture);
            }
        }
        
        public static string Const_Label_Journey_Score {
            get {
                return ResourceManager.GetString("Const_Label_Journey_Score", resourceCulture);
            }
        }
        
        public static string Const_Label_Not_Registered {
            get {
                return ResourceManager.GetString("Const_Label_Not_Registered", resourceCulture);
            }
        }
        
        public static string Const_Language_en {
            get {
                return ResourceManager.GetString("Const_Language_en", resourceCulture);
            }
        }
        
        public static string Const_Language_fr {
            get {
                return ResourceManager.GetString("Const_Language_fr", resourceCulture);
            }
        }
        
        public static string Const_Label_Export {
            get {
                return ResourceManager.GetString("Const_Label_Export", resourceCulture);
            }
        }
        
        public static string Const_Label_Export_Column1 {
            get {
                return ResourceManager.GetString("Const_Label_Export_Column1", resourceCulture);
            }
        }
        
        public static string Const_Label_Export_Column2 {
            get {
                return ResourceManager.GetString("Const_Label_Export_Column2", resourceCulture);
            }
        }
        
        public static string Const_Label_Export_Column3 {
            get {
                return ResourceManager.GetString("Const_Label_Export_Column3", resourceCulture);
            }
        }
        
        public static string Const_Label_Export_Column4 {
            get {
                return ResourceManager.GetString("Const_Label_Export_Column4", resourceCulture);
            }
        }
        
        public static string Const_Label_Export_Column5 {
            get {
                return ResourceManager.GetString("Const_Label_Export_Column5", resourceCulture);
            }
        }
        
        public static string Const_Label_Export_Column6 {
            get {
                return ResourceManager.GetString("Const_Label_Export_Column6", resourceCulture);
            }
        }
        
        public static string Const_Label_Export_FileName {
            get {
                return ResourceManager.GetString("Const_Label_Export_FileName", resourceCulture);
            }
        }
        
        public static string Const_Label_Export_Subject {
            get {
                return ResourceManager.GetString("Const_Label_Export_Subject", resourceCulture);
            }
        }
        
        public static string Const_Label_Calendar_1 {
            get {
                return ResourceManager.GetString("Const_Label_Calendar_1", resourceCulture);
            }
        }
        
        public static string Const_Label_Calendar_2 {
            get {
                return ResourceManager.GetString("Const_Label_Calendar_2", resourceCulture);
            }
        }
        
        public static string Const_Label_Calendar_3 {
            get {
                return ResourceManager.GetString("Const_Label_Calendar_3", resourceCulture);
            }
        }
        
        public static string Const_Label_Calendar_4 {
            get {
                return ResourceManager.GetString("Const_Label_Calendar_4", resourceCulture);
            }
        }
        
        public static string Const_Label_Calendar_5 {
            get {
                return ResourceManager.GetString("Const_Label_Calendar_5", resourceCulture);
            }
        }
        
        public static string Const_Label_Rate_Title {
            get {
                return ResourceManager.GetString("Const_Label_Rate_Title", resourceCulture);
            }
        }
        
        public static string Const_Label_Rate_Message {
            get {
                return ResourceManager.GetString("Const_Label_Rate_Message", resourceCulture);
            }
        }
        
        public static string Const_Label_Rate_ButtonCancel {
            get {
                return ResourceManager.GetString("Const_Label_Rate_ButtonCancel", resourceCulture);
            }
        }
        
        public static string Const_Label_Rate_ButtonYes {
            get {
                return ResourceManager.GetString("Const_Label_Rate_ButtonYes", resourceCulture);
            }
        }
        
        public static string Const_Label_Rate_ButtonRemind {
            get {
                return ResourceManager.GetString("Const_Label_Rate_ButtonRemind", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_0 {
            get {
                return ResourceManager.GetString("Const_Event_Type_0", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_1 {
            get {
                return ResourceManager.GetString("Const_Event_Type_1", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_2 {
            get {
                return ResourceManager.GetString("Const_Event_Type_2", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_3 {
            get {
                return ResourceManager.GetString("Const_Event_Type_3", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_4 {
            get {
                return ResourceManager.GetString("Const_Event_Type_4", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_5 {
            get {
                return ResourceManager.GetString("Const_Event_Type_5", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_6 {
            get {
                return ResourceManager.GetString("Const_Event_Type_6", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_7 {
            get {
                return ResourceManager.GetString("Const_Event_Type_7", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_8 {
            get {
                return ResourceManager.GetString("Const_Event_Type_8", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_9 {
            get {
                return ResourceManager.GetString("Const_Event_Type_9", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_10 {
            get {
                return ResourceManager.GetString("Const_Event_Type_10", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_11 {
            get {
                return ResourceManager.GetString("Const_Event_Type_11", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_12 {
            get {
                return ResourceManager.GetString("Const_Event_Type_12", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_13 {
            get {
                return ResourceManager.GetString("Const_Event_Type_13", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_14 {
            get {
                return ResourceManager.GetString("Const_Event_Type_14", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_15 {
            get {
                return ResourceManager.GetString("Const_Event_Type_15", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_16 {
            get {
                return ResourceManager.GetString("Const_Event_Type_16", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_17 {
            get {
                return ResourceManager.GetString("Const_Event_Type_17", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_18 {
            get {
                return ResourceManager.GetString("Const_Event_Type_18", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_19 {
            get {
                return ResourceManager.GetString("Const_Event_Type_19", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_20 {
            get {
                return ResourceManager.GetString("Const_Event_Type_20", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_21 {
            get {
                return ResourceManager.GetString("Const_Event_Type_21", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_22 {
            get {
                return ResourceManager.GetString("Const_Event_Type_22", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_23 {
            get {
                return ResourceManager.GetString("Const_Event_Type_23", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_24 {
            get {
                return ResourceManager.GetString("Const_Event_Type_24", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_25 {
            get {
                return ResourceManager.GetString("Const_Event_Type_25", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_26 {
            get {
                return ResourceManager.GetString("Const_Event_Type_26", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_27 {
            get {
                return ResourceManager.GetString("Const_Event_Type_27", resourceCulture);
            }
        }
        
        public static string Const_Event_Type_28 {
            get {
                return ResourceManager.GetString("Const_Event_Type_28", resourceCulture);
            }
        }
        
        public static string Const_Menu_Dashboard {
            get {
                return ResourceManager.GetString("Const_Menu_Dashboard", resourceCulture);
            }
        }
        
        public static string Const_Menu_ScoreHistory {
            get {
                return ResourceManager.GetString("Const_Menu_ScoreHistory", resourceCulture);
            }
        }
        
        public static string Const_Menu_YourJourneys {
            get {
                return ResourceManager.GetString("Const_Menu_YourJourneys", resourceCulture);
            }
        }
        
        public static string Const_Menu_Expenses {
            get {
                return ResourceManager.GetString("Const_Menu_Expenses", resourceCulture);
            }
        }
        
        public static string Const_Menu_UserGuide {
            get {
                return ResourceManager.GetString("Const_Menu_UserGuide", resourceCulture);
            }
        }
        
        public static string Const_Menu_Terms {
            get {
                return ResourceManager.GetString("Const_Menu_Terms", resourceCulture);
            }
        }
        
        public static string Const_Menu_DrivingTips {
            get {
                return ResourceManager.GetString("Const_Menu_DrivingTips", resourceCulture);
            }
        }
        
        public static string Const_Menu_Settings {
            get {
                return ResourceManager.GetString("Const_Menu_Settings", resourceCulture);
            }
        }
        
        public static string Const_Menu_EmergencyAdvice {
            get {
                return ResourceManager.GetString("Const_Menu_EmergencyAdvice", resourceCulture);
            }
        }
        
        public static string Const_Menu_RefreshData {
            get {
                return ResourceManager.GetString("Const_Menu_RefreshData", resourceCulture);
            }
        }
        
        public static string Const_Button_SignIn {
            get {
                return ResourceManager.GetString("Const_Button_SignIn", resourceCulture);
            }
        }
        
        public static string Const_Button_SignOut {
            get {
                return ResourceManager.GetString("Const_Button_SignOut", resourceCulture);
            }
        }
        
        public static string Const_Button_Accept {
            get {
                return ResourceManager.GetString("Const_Button_Accept", resourceCulture);
            }
        }
        
        public static string Const_Button_Close {
            get {
                return ResourceManager.GetString("Const_Button_Close", resourceCulture);
            }
        }
        
        public static string Const_Button_Cancel {
            get {
                return ResourceManager.GetString("Const_Button_Cancel", resourceCulture);
            }
        }
        
        public static string Const_Button_Select {
            get {
                return ResourceManager.GetString("Const_Button_Select", resourceCulture);
            }
        }
        
        public static string Const_Button_Add {
            get {
                return ResourceManager.GetString("Const_Button_Add", resourceCulture);
            }
        }
        
        public static string Const_Button_Remove {
            get {
                return ResourceManager.GetString("Const_Button_Remove", resourceCulture);
            }
        }
        
        public static string Const_Button_Select_All {
            get {
                return ResourceManager.GetString("Const_Button_Select_All", resourceCulture);
            }
        }
        
        public static string Const_Button_Deselect_All {
            get {
                return ResourceManager.GetString("Const_Button_Deselect_All", resourceCulture);
            }
        }
        
        public static string Const_Button_Submit {
            get {
                return ResourceManager.GetString("Const_Button_Submit", resourceCulture);
            }
        }
        
        public static string Const_Button_Registration_1_Next {
            get {
                return ResourceManager.GetString("Const_Button_Registration_1_Next", resourceCulture);
            }
        }
        
        public static string Const_Button_Registration_2_Next {
            get {
                return ResourceManager.GetString("Const_Button_Registration_2_Next", resourceCulture);
            }
        }
        
        public static string Const_Button_Registration_3_Next {
            get {
                return ResourceManager.GetString("Const_Button_Registration_3_Next", resourceCulture);
            }
        }
        
        public static string Const_Button_Registration_4_Next {
            get {
                return ResourceManager.GetString("Const_Button_Registration_4_Next", resourceCulture);
            }
        }
        
        public static string Const_Button_Dashboard_Tab1 {
            get {
                return ResourceManager.GetString("Const_Button_Dashboard_Tab1", resourceCulture);
            }
        }
        
        public static string Const_Button_Dashboard_Tab2 {
            get {
                return ResourceManager.GetString("Const_Button_Dashboard_Tab2", resourceCulture);
            }
        }
        
        public static string Const_Button_Dashboard_Tab3 {
            get {
                return ResourceManager.GetString("Const_Button_Dashboard_Tab3", resourceCulture);
            }
        }
        
        public static string Const_Button_Journeys_Tab1 {
            get {
                return ResourceManager.GetString("Const_Button_Journeys_Tab1", resourceCulture);
            }
        }
        
        public static string Const_Button_Journeys_Tab2 {
            get {
                return ResourceManager.GetString("Const_Button_Journeys_Tab2", resourceCulture);
            }
        }
        
        public static string Const_Button_Journeys_Tab3 {
            get {
                return ResourceManager.GetString("Const_Button_Journeys_Tab3", resourceCulture);
            }
        }
        
        public static string Const_Button_Notifications_Tab1 {
            get {
                return ResourceManager.GetString("Const_Button_Notifications_Tab1", resourceCulture);
            }
        }
        
        public static string Const_Button_Notifications_Tab2 {
            get {
                return ResourceManager.GetString("Const_Button_Notifications_Tab2", resourceCulture);
            }
        }
        
        public static string Const_Button_Notifications_Tab3 {
            get {
                return ResourceManager.GetString("Const_Button_Notifications_Tab3", resourceCulture);
            }
        }
        
        public static string Const_Button_Map_Tab1 {
            get {
                return ResourceManager.GetString("Const_Button_Map_Tab1", resourceCulture);
            }
        }
        
        public static string Const_Button_Map_Tab2 {
            get {
                return ResourceManager.GetString("Const_Button_Map_Tab2", resourceCulture);
            }
        }
        
        public static string Const_Button_Map_Tab3 {
            get {
                return ResourceManager.GetString("Const_Button_Map_Tab3", resourceCulture);
            }
        }
        
        public static string Const_Button_Score_History {
            get {
                return ResourceManager.GetString("Const_Button_Score_History", resourceCulture);
            }
        }
        
        public static string Const_Button_Map {
            get {
                return ResourceManager.GetString("Const_Button_Map", resourceCulture);
            }
        }
        
        public static string Const_Button_Journeys {
            get {
                return ResourceManager.GetString("Const_Button_Journeys", resourceCulture);
            }
        }
        
        public static string Const_Button_Driving_Tips {
            get {
                return ResourceManager.GetString("Const_Button_Driving_Tips", resourceCulture);
            }
        }
        
        public static string Const_Button_Refine {
            get {
                return ResourceManager.GetString("Const_Button_Refine", resourceCulture);
            }
        }
        
        public static string Const_Button_Search {
            get {
                return ResourceManager.GetString("Const_Button_Search", resourceCulture);
            }
        }
        
        public static string Const_Button_View_Map {
            get {
                return ResourceManager.GetString("Const_Button_View_Map", resourceCulture);
            }
        }
        
        public static string Const_Button_View_On_Map {
            get {
                return ResourceManager.GetString("Const_Button_View_On_Map", resourceCulture);
            }
        }
        
        public static string Const_Button_View_Map_Info {
            get {
                return ResourceManager.GetString("Const_Button_View_Map_Info", resourceCulture);
            }
        }
        
        public static string Const_Button_View_Journey {
            get {
                return ResourceManager.GetString("Const_Button_View_Journey", resourceCulture);
            }
        }
        
        public static string Const_Button_View_Info {
            get {
                return ResourceManager.GetString("Const_Button_View_Info", resourceCulture);
            }
        }
        
        public static string Const_Button_Confirm_1 {
            get {
                return ResourceManager.GetString("Const_Button_Confirm_1", resourceCulture);
            }
        }
        
        public static string Const_Button_Confirm_2 {
            get {
                return ResourceManager.GetString("Const_Button_Confirm_2", resourceCulture);
            }
        }
        
        public static string Const_Button_Confirm_3 {
            get {
                return ResourceManager.GetString("Const_Button_Confirm_3", resourceCulture);
            }
        }
        
        public static string Const_Button_Confirm_4 {
            get {
                return ResourceManager.GetString("Const_Button_Confirm_4", resourceCulture);
            }
        }
        
        public static string Const_Button_Select_Vehicle {
            get {
                return ResourceManager.GetString("Const_Button_Select_Vehicle", resourceCulture);
            }
        }
        
        public static string Const_Button_Add_Odometer_Reading {
            get {
                return ResourceManager.GetString("Const_Button_Add_Odometer_Reading", resourceCulture);
            }
        }
        
        public static string Const_Button_Next_Journey_Only {
            get {
                return ResourceManager.GetString("Const_Button_Next_Journey_Only", resourceCulture);
            }
        }
        
        public static string Const_Button_Set_End_Time {
            get {
                return ResourceManager.GetString("Const_Button_Set_End_Time", resourceCulture);
            }
        }
        
        public static string Const_Button_Set_Time {
            get {
                return ResourceManager.GetString("Const_Button_Set_Time", resourceCulture);
            }
        }
        
        public static string Const_Button_Select_Bluetooth {
            get {
                return ResourceManager.GetString("Const_Button_Select_Bluetooth", resourceCulture);
            }
        }
        
        public static string Const_Button_Pair_Vehicle {
            get {
                return ResourceManager.GetString("Const_Button_Pair_Vehicle", resourceCulture);
            }
        }
        
        public static string Const_Button_Create_Vehicle {
            get {
                return ResourceManager.GetString("Const_Button_Create_Vehicle", resourceCulture);
            }
        }
        
        public static string Const_Button_Send {
            get {
                return ResourceManager.GetString("Const_Button_Send", resourceCulture);
            }
        }
        
        public static string Const_Button_Send_Incident {
            get {
                return ResourceManager.GetString("Const_Button_Send_Incident", resourceCulture);
            }
        }
        
        public static string Const_Button_Try_Again {
            get {
                return ResourceManager.GetString("Const_Button_Try_Again", resourceCulture);
            }
        }
        
        public static string Const_Button_Manage_Vehicle_Step_1 {
            get {
                return ResourceManager.GetString("Const_Button_Manage_Vehicle_Step_1", resourceCulture);
            }
        }
        
        public static string Const_Button_Manage_Vehicle_Step_2 {
            get {
                return ResourceManager.GetString("Const_Button_Manage_Vehicle_Step_2", resourceCulture);
            }
        }
        
        public static string Const_Button_Manage_Vehicle_Step_3 {
            get {
                return ResourceManager.GetString("Const_Button_Manage_Vehicle_Step_3", resourceCulture);
            }
        }
        
        public static string Const_Button_Manage_Vehicle_Step_4 {
            get {
                return ResourceManager.GetString("Const_Button_Manage_Vehicle_Step_4", resourceCulture);
            }
        }
        
        public static string Const_Button_Manage_Vehicle_Step_5 {
            get {
                return ResourceManager.GetString("Const_Button_Manage_Vehicle_Step_5", resourceCulture);
            }
        }
        
        public static string Const_Button_Confirm {
            get {
                return ResourceManager.GetString("Const_Button_Confirm", resourceCulture);
            }
        }
        
        public static string Const_Button_View_Journeys {
            get {
                return ResourceManager.GetString("Const_Button_View_Journeys", resourceCulture);
            }
        }
        
        public static string Const_Button_View_All_Journeys {
            get {
                return ResourceManager.GetString("Const_Button_View_All_Journeys", resourceCulture);
            }
        }
        
        public static string Const_Button_More {
            get {
                return ResourceManager.GetString("Const_Button_More", resourceCulture);
            }
        }
        
        public static string Const_Button_Join {
            get {
                return ResourceManager.GetString("Const_Button_Join", resourceCulture);
            }
        }
        
        public static string Const_Placeholder_UserName {
            get {
                return ResourceManager.GetString("Const_Placeholder_UserName", resourceCulture);
            }
        }
        
        public static string Const_Placeholder_Password {
            get {
                return ResourceManager.GetString("Const_Placeholder_Password", resourceCulture);
            }
        }
        
        public static string Const_Placeholder_New_Password {
            get {
                return ResourceManager.GetString("Const_Placeholder_New_Password", resourceCulture);
            }
        }
        
        public static string Const_Placeholder_Enter {
            get {
                return ResourceManager.GetString("Const_Placeholder_Enter", resourceCulture);
            }
        }
        
        public static string Const_Placeholder_Position {
            get {
                return ResourceManager.GetString("Const_Placeholder_Position", resourceCulture);
            }
        }
        
        public static string Const_Placeholder_ReType_Password {
            get {
                return ResourceManager.GetString("Const_Placeholder_ReType_Password", resourceCulture);
            }
        }
        
        public static string Const_Placeholder_Select_Vehicle {
            get {
                return ResourceManager.GetString("Const_Placeholder_Select_Vehicle", resourceCulture);
            }
        }
        
        public static string Const_Placeholder_Mobile_Number {
            get {
                return ResourceManager.GetString("Const_Placeholder_Mobile_Number", resourceCulture);
            }
        }
        
        public static string Const_Placeholder_Company_Name {
            get {
                return ResourceManager.GetString("Const_Placeholder_Company_Name", resourceCulture);
            }
        }
        
        public static string Const_Placeholder_Start_Date {
            get {
                return ResourceManager.GetString("Const_Placeholder_Start_Date", resourceCulture);
            }
        }
        
        public static string Const_Placeholder_End_Date {
            get {
                return ResourceManager.GetString("Const_Placeholder_End_Date", resourceCulture);
            }
        }
        
        public static string Const_Placeholder_Optional {
            get {
                return ResourceManager.GetString("Const_Placeholder_Optional", resourceCulture);
            }
        }
        
        public static string Const_Placeholder_Fleet_Code {
            get {
                return ResourceManager.GetString("Const_Placeholder_Fleet_Code", resourceCulture);
            }
        }
        
        public static string Const_Placeholder_DOB {
            get {
                return ResourceManager.GetString("Const_Placeholder_DOB", resourceCulture);
            }
        }
        
        public static string Const_Label_Group_Score {
            get {
                return ResourceManager.GetString("Const_Label_Group_Score", resourceCulture);
            }
        }
        
        public static string Const_Label_Business_Score {
            get {
                return ResourceManager.GetString("Const_Label_Business_Score", resourceCulture);
            }
        }
        
        public static string Const_Label_Team_Score {
            get {
                return ResourceManager.GetString("Const_Label_Team_Score", resourceCulture);
            }
        }
        
        public static string Const_Label_Difference {
            get {
                return ResourceManager.GetString("Const_Label_Difference", resourceCulture);
            }
        }
        
        public static string Const_Label_Speed_Unit {
            get {
                return ResourceManager.GetString("Const_Label_Speed_Unit", resourceCulture);
            }
        }
        
        public static string Const_Label_NoPDFViewer {
            get {
                return ResourceManager.GetString("Const_Label_NoPDFViewer", resourceCulture);
            }
        }
        
        public static string Const_Label_Score {
            get {
                return ResourceManager.GetString("Const_Label_Score", resourceCulture);
            }
        }
        
        public static string Const_Label_Ranking {
            get {
                return ResourceManager.GetString("Const_Label_Ranking", resourceCulture);
            }
        }
    }
}
